layout_spectrum: 0.6616541
color:
  saturation: 0.8941103
  lightness: 0.5469925
  brandStrength: 0.7606516
  brandColors:
    - '#FFFFFF'
    - '#0A080D'
    - '#736F6C'
    - '#434345'
    - '#97959A'
  rhythmicContrast: 0.7631579
typography_spectrum: 0.6516291
name: LisaTrujillo
