name: Fast English Mastery
favicon: null
layout_spectrum: 0.1948622
typography_spectrum: 0.358396
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Master Academic English Fast with Lisa Trujillo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c2127'
    - '#656661'
    - '#9cbad6'
    - '#ff91aa'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.8201754
purpose: []
