name: LisaTrujillo
favicon: null
layout_spectrum: 0.1948622
typography_spectrum: 0.358396
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Master Academic English Fast with Lisa Trujillo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#0A080D'
    - '#736F6C'
    - '#434345'
    - '#97959A'
  brandStrength: 0.7606516
  lightness: 0.9110276
  saturation: 0.8358396
  rhythmicContrast: 0.8201754
purpose: []
