title: Master Academic English Fast with Lisa Trujillo
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.9375
  rhythmicContrast: 0.8201754
  brandColors:
    - '#ffffff'
    - '#88a201'
    - '#000000'
    - '#21a8f6'
    - '#3e4950'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Fast English Mastery
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.358396
layout_spectrum: 0.6795953
